### ISSUE TITLE
Is the example interval correct?

### ISSUE THREAD

**Issue by hakank** [celinehocquette/magicpopper#3]
Running the interval example give the following solution:
```
python3 popper.py examples/interval        
NO MORE SOLUTIONS
********** SOLUTION **********
Precision:1.00 Recall:1.00 TP:26 FN:0 TN:22 FP:0 Size:26
interval(-36).
interval(-11).
interval(19).
interval(23).
interval(13).
interval(-20).
interval(-15).
interval(-19).
interval(-27).
interval(4).
interval(-29).
interval(-1).
interval(-28).
interval(-9).
interval(-34).
interval(-30).
interval(-8).
interval(-14).
interval(7).
interval(-35).
interval(2).
interval(5).
interval(-16).
interval(12).
interval(-21).
interval(9).
******************************
```

which is just a listing of the positive instances. 

Is this the correct solution? bk.pl and bias.pl include a lot of predicates which seems to indicate that the solutions should use some of these predicates.

**Comment by celinehocquette** [comment]
Yes, this is an example MagicPopper struggles with. The reason is that it cannot reason from multiple examples jointly to identify the thresholds, but instead considers each example individually when identifying magic values.

**Comment by hakank** [comment]
Ah, I see, Thanks for the explanation.
