### ISSUE TITLE
Installation of Popper and magicpopper.

### ISSUE THREAD

**Issue by pauljurczak** [celinehocquette/magicpopper#9]
I installed Popper un Ubuntu 22.04.2 with Python 3.11.2 and run an example from https://github.com/logic-and-learning-lab/Popper/#library-usage with no problems. Afterwards, I installed magicpopper from https://github.com/celinehocquette/magicpopper/tree/main/magicpopper using `pip install .`. The installation overwrites `popper-ilp-2.0.0` and the example no longer works. This is the error message:
```
(.venv) paul@desktop:~/st-python/prolog$  /usr/bin/env /home/paul/st-python/prolog/.venv/bin/python /home/paul/.vscode/extensions/ms-python.python-2023.4.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 36639 -- /home/paul/st-python/prolog/popper-0.py 
Traceback (most recent call last):
  File "/home/paul/st-python/prolog/popper-0.py", line 4, in <module>
    settings = Settings(kbpath='kinship')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul/st-python/prolog/.venv/lib/python3.11/site-packages/popper/util.py", line 393, in __init__
    with open(self.bias_file) as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''
```
Can these two, Popper and magicpopper, be installed together? Does it even make sense? I'm just learning about ILP, so these questions may be completely clueless.

**Comment by andrewcropper** [comment]
Hi,

They cannot be installed together, sorry. I suggest simply cloning each repository separately. 

In addition, MagicPopper will soon (hopefully) be merged into the main Popper repo.

Kind regards,

Andrew

**Comment by pauljurczak** [comment]
Thank you.
